name: Sanity Build

on: [pull_request]

jobs:
  sanity-build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        apps: [frontend, server]
    name: ${{ matrix.apps }} Sanity Build
    runs-on: ubuntu-latest
    env:
      BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      XDG_CONFIG_HOME: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
          registries: |
            @navikt:https://npm.pkg.github.com/|$BUN_AUTH_TOKEN

      - name: Rename bunfig to global config name
        run: mv bunfig.toml .bunfig.toml

      - name: Install root dependencies
        shell: bash
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install ${{ matrix.apps }} dependencies
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun install --frozen-lockfile --ignore-scripts

      - name: Restore caches for ${{ matrix.apps }}
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ runner.os }}-${{ matrix.apps }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}

      - name: Typecheck ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun run typecheck

      - name: Lint ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun run lint

      - name: Test ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun test

      - name: Save caches for ${{ matrix.apps }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: always()
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ runner.os }}-${{ matrix.apps }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}
