name: Sanity Build

on: [pull_request]

jobs:
  sanity-build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        apps: [frontend, server]
    name: ${{ matrix.apps }} Sanity Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Symlink bunfig to repo root
        run: ln -s ${{ matrix.apps }}/bunfig.toml bunfig.toml

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registries: |
            https://registry.npmjs.org/
            @navikt:https://npm.pkg.github.com/|$BUN_AUTH_TOKEN
      
      - name: Install root dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install ${{ matrix.apps }} dependencies
        shell: bash
        working-directory: ${{ matrix.apps }}
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install ${{ matrix.apps }} dependencies
        shell: bash
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          cd ${{ matrix.apps }}
          bun install --frozen-lockfile --ignore-scripts

      - name: Restore caches for ${{ matrix.apps }}
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ runner.os }}-${{ matrix.apps }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}

      - name: Typecheck ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun run typecheck

      - name: Lint ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun run lint

      - name: Test ${{ matrix.apps }}
        shell: bash
        run: |
          cd ${{ matrix.apps }}
          bun test

      - name: Save caches for ${{ matrix.apps }}
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ${{matrix.apps}}/.tsbuildinfo
          key: ${{ runner.os }}-${{ matrix.apps }}-${{ hashFiles(format('{0}/tsconfig.json', matrix.apps)) }}
